### PR TITLE
(XL)  Refactor fetch calls for re-usability.

### PR DESCRIPTION
**Pull request by mseaward**
Add methods to build a transfer transaction with the correct fees set on it.
**warning**: this is incomplete and need further integration with the scatter ui

Relates to #13 but does not close.

### CODE REVIEW

**Comment by belakon1975** [comment]
@mseaward @MuffinLightning  please estimate!

**Comment by mseaward** [comment]
> @mseaward @MuffinLightning please estimate!

@belakon1975 this is a pull request for work already outlined in an issue. The issue (Jira equivalent of tickets/issue/stories) on GitHub has the time estimate I believe.

**Comment by mseaward** [comment]
This pull request ties together some code we need to proceed with transfer functionality. Pending items for transfer functionality are: 
* retrieval of keys from Scatter encrypted storage to allow us to sign the transaction
* broadcasting transaction after it has been signed

**Review by MuffinLightning — APPROVED** [review]
looks good

**Pull request merged**
